
feature: "germinal"
task_type: "binary"
magnification: "10x"
loss: ["wCE"]
name: "$model_$feature_$mag_$augment_$dim_$step-" 
ratio: 0.9
batch_size: 4
image_dims: 1024
epochs: 100
augmentation: 
        methods: [["Flip","Rotate90"]]
        saturation: [0.5,1.2]
        brightness: 0.4
        hue: 0.05
        contrast: [0.8,1.5]
        flip_prob: 0.5
        rotate_prob: 0.5
        color_prob: 0.5
normalize:
        methods: ["Scale","StandardizeDataset"]
        channel_std: [0.247, 0.270, 0.227 ]
        channel_mean: [0.633, 0.527, 0.629 ]        
num_classes: 1 
weights: [56.10]
model: 
        network: "unet"
        filters: [32,64,128,256,512]
        final_activation: "sigmoid"
        dropout: 0
learning_rate: 0.001 
gpu_num: 2
metric: "dice_coef" 
threshold: 0.75
early_stopping:
        metric: [0.85,0.8]
        epochs: [40, 80]
step: 512
